// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModeController from "./mode_controller"
application.register("mode", ModeController)

import AddRemoveController from "./add_remove_controller"
application.register("add-remove", AddRemoveController)
